import React, { useMemo } from 'react';
import { View, Text, TouchableOpacity, StyleSheet, Share, Alert } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { WebView } from 'react-native-webview';
import Icon from 'react-native-vector-icons/Feather';
import { BaseStyle } from '../constans/Style';
import { blackColor, borderLightColor, grayColor, redColor, whiteColor } from '../constans/Color';
import { style } from '../constans/Fonts';
import {
  RECEIPT_BRAND,
  RECEIPT_SCREEN_TITLE,
  RECEIPT_SHARE_BUTTON,
  RECEIPT_SUBTITLE,
  TXN_BREAKDOWN_GROSS,
  TXN_BREAKDOWN_NET,
  TXN_BREAKDOWN_PAID,
  TXN_BREAKDOWN_PLATFORM_FEE,
  TXN_BREAKDOWN_STRIPE_FEE,
} from '../constans/Constants';
import { widthPercentageToDP as wp, heightPercentageToDP as hp } from '../utils';

const { flex, flexDirectionRow, alignItemsCenter } = BaseStyle;

const money = (value, currency = '$') =>
  `${currency}${Number(value || 0).toLocaleString('en-US', {
    minimumFractionDigits: 2,
    maximumFractionDigits: 2,
  })}`;

const escapeHtml = value =>
  String(value ?? '').replace(
    /[&<>"']/g,
    ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[ch],
  );

/**
 * The lines a receipt shows. Sellers get the full split (it's their earning
 * being itemized); buyers get what they paid, since the platform's cut and the
 * seller's take-home aren't theirs to see.
 */
const buildLines = (item, currency, isSeller) => {
  const lines = [
    { label: isSeller ? TXN_BREAKDOWN_GROSS : TXN_BREAKDOWN_PAID, value: money(item.gross ?? item.amount, currency) },
  ];
  if (isSeller && item.platformFee != null) {
    lines.push({ label: TXN_BREAKDOWN_PLATFORM_FEE, value: `-${money(item.platformFee, currency)}` });
  }
  if (isSeller && item.stripeFee != null) {
    lines.push({ label: TXN_BREAKDOWN_STRIPE_FEE, value: `-${money(item.stripeFee, currency)}` });
  }
  if (isSeller && item.net != null) {
    lines.push({ label: TXN_BREAKDOWN_NET, value: money(item.net, currency), total: true });
  }
  return lines;
};

const buildHtml = ({ item, lines, statusLabel }) => `<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      * { box-sizing: border-box; }
      body { margin: 0; padding: 24px 20px 40px; background: #F4F4F5;
             font-family: -apple-system, Roboto, Helvetica, Arial, sans-serif; color: #111; }
      .sheet { background: #fff; border-radius: 16px; padding: 24px 20px;
               box-shadow: 0 1px 3px rgba(0,0,0,.08); max-width: 560px; margin: 0 auto; }
      h1 { font-size: 20px; margin: 0; letter-spacing: -.2px; }
      .sub { font-size: 13px; color: #6B6B6B; margin: 4px 0 0; }
      hr { border: 0; border-top: 1px solid #ECECEC; margin: 18px 0; }
      .meta { font-size: 13px; }
      .meta div { display: flex; justify-content: space-between; gap: 16px; padding: 5px 0; }
      .meta .k { color: #6B6B6B; }
      .meta .v { color: #111; font-weight: 500; text-align: right; }
      .total { border-top: 1px solid #ECECEC; margin-top: 8px; padding-top: 12px !important; }
      .total .k, .total .v { font-weight: 700; font-size: 15px; color: #111; }
      .pill { display: inline-block; font-size: 11px; font-weight: 600; border-radius: 999px;
              padding: 3px 10px; background: #F1F1F1; color: #555; }
      .foot { font-size: 11px; color: #9A9A9A; text-align: center; margin-top: 18px; }
    </style>
  </head>
  <body>
    <div class="sheet">
      <h1>${escapeHtml(RECEIPT_BRAND)}</h1>
      <p class="sub">${escapeHtml(RECEIPT_SUBTITLE)}</p>
      <hr />
      <div class="meta">
        <div><span class="k">Receipt #</span><span class="v">${escapeHtml(item.id)}</span></div>
        <div><span class="k">Date</span><span class="v">${escapeHtml(item.date)}</span></div>
        ${item.bookingId ? `<div><span class="k">Booking</span><span class="v">#${escapeHtml(item.bookingId)}</span></div>` : ''}
        <div><span class="k">Description</span><span class="v">${escapeHtml(item.title)}</span></div>
        <div><span class="k">Status</span><span class="v"><span class="pill">${escapeHtml(statusLabel)}</span></span></div>
      </div>
      <hr />
      <div class="meta">
        ${lines
          .map(
            l =>
              `<div class="${l.total ? 'total' : ''}"><span class="k">${escapeHtml(l.label)}</span><span class="v">${escapeHtml(l.value)}</span></div>`,
          )
          .join('')}
      </div>
      <p class="foot">This receipt was generated by ${escapeHtml(RECEIPT_BRAND)}.</p>
    </div>
  </body>
</html>`;

/**
 * A single transaction's receipt.
 *
 * Params: { item } — a row from mapWalletTxn — plus { role, currency, statusLabel }.
 *
 * Rendered as a web page rather than a PDF: the app has no filesystem or PDF
 * module, so there's nowhere to write a file to. Share hands the same details
 * to whatever the user picks (mail, chat, Files/Drive), which is what they'd do
 * with a downloaded copy anyway.
 */
const ReceiptScreen = ({ navigation, route }) => {
  const item = route.params?.item;
  const role = route.params?.role || 'buyer';
  const currency = route.params?.currency || '$';
  const statusLabel = route.params?.statusLabel || '';
  const isSeller = role === 'seller';

  const lines = useMemo(
    () => (item ? buildLines(item, currency, isSeller) : []),
    [item, currency, isSeller],
  );
  const html = useMemo(
    () => (item ? buildHtml({ item, lines, statusLabel }) : ''),
    [item, lines, statusLabel],
  );

  const handleShare = async () => {
    if (!item) return;
    const body = [
      `${RECEIPT_BRAND} — ${RECEIPT_SUBTITLE}`,
      '',
      `Receipt #: ${item.id}`,
      `Date: ${item.date}`,
      item.bookingId ? `Booking: #${item.bookingId}` : '',
      `Description: ${item.title}`,
      statusLabel ? `Status: ${statusLabel}` : '',
      '',
      ...lines.map(l => `${l.label}: ${l.value}`),
    ]
      .filter(Boolean)
      .join('\n');
    try {
      await Share.share({ title: `${RECEIPT_BRAND} receipt #${item.id}`, message: body });
    } catch (error) {
      Alert.alert('', 'Could not share this receipt. Please try again.');
    }
  };

  if (!item) return null;

  return (
    <SafeAreaView style={[flex, styles.safeArea]} edges={['top', 'bottom']}>
      <View style={[styles.header, flexDirectionRow, alignItemsCenter]}>
        <TouchableOpacity style={styles.iconBtn} onPress={() => navigation.goBack()}>
          <Icon name="x" size={22} color={blackColor} />
        </TouchableOpacity>
        <Text style={[styles.title, style.fontWeightMedium]} numberOfLines={1}>
          {RECEIPT_SCREEN_TITLE}
        </Text>
        <TouchableOpacity style={styles.iconBtn} onPress={handleShare}>
          <Icon name="share-2" size={19} color={redColor} />
        </TouchableOpacity>
      </View>

      <WebView
        style={flex}
        originWhitelist={['*']}
        source={{ html }}
        javaScriptEnabled={false}
        showsVerticalScrollIndicator={false}
      />

      <TouchableOpacity style={[styles.shareBtn, flexDirectionRow]} onPress={handleShare} activeOpacity={0.85}>
        <Icon name="share-2" size={16} color={whiteColor} />
        <Text style={[styles.shareText, style.fontWeightMedium]}>{RECEIPT_SHARE_BUTTON}</Text>
      </TouchableOpacity>
    </SafeAreaView>
  );
};

export default ReceiptScreen;

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: whiteColor },
  header: {
    width: '100%',
    paddingHorizontal: wp(3),
    paddingVertical: hp(1.2),
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: borderLightColor,
    gap: wp(2),
  },
  iconBtn: { width: wp(9), height: wp(9), alignItems: 'center', justifyContent: 'center', flexShrink: 0 },
  title: { flex: 1, fontSize: style.fontSizeNormal2x.fontSize, color: blackColor },
  shareBtn: {
    margin: wp(4),
    minHeight: 48,
    borderRadius: 12,
    backgroundColor: redColor,
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
  },
  shareText: { fontSize: style.fontSizeNormal2x.fontSize, color: whiteColor },
  placeholder: { color: grayColor },
});
